import mongoose from "mongoose";

const addorderSchema = new mongoose.Schema({
  orderDate: { type: String, required: false, trim: true },
  orderId: { type: String, required: false, trim: true },
  productId: { type: String, required: false, trim: true },
  productName: { type: String, required: false, trim: true },
  orderNote: { type: String, required: false, trim: true },
  identifierType: { type: String, required: false, trim: true },
  identifier: { type: String, required: false, trim: true },
  category: { type: String, required: false, trim: true },
  condition: { type: String, required: false, trim: true },
  purchasePrice: { type: Number, required: false, trim: true },
  quantity: { type: Number, required: false, trim: true },
  commision: { type: Number, required: false, trim: true },
  tax: { type: String, required: false, trim: true },
  listedPrice: { type: Number, required: false, trim: true },
  marketplaces: { type: String, required: false, trim: true },
  recipientName: { type: String, required: false, trim: true },
  phoneNumber: { type: String, required: false, trim: true },
  buyerEmail: { type: String, required: false, trim: true },
  addressOne: { type: String, required: false, trim: true },
  addressTwo: { type: String, required: false, trim: true },
  city: { type: String, required: false, trim: true },
  state: { type: String, required: false, trim: true },
  country: { type: String, required: false, trim: true },
  postalCode: { type: Number, required: false, trim: true },
  packageWeight: { type: Number, required: false, trim: true },
  lbs: { type: Number, required: false, trim: true },
  packageDimensions: { type: Number, required: false, trim: true },
  width: { type: Number, required: false, trim: true },
  height: { type: Number, required: false, trim: true },
  userid: { type: String, required: false, trim: true },
  orderStatus: { type: String, required: false, trim: true },
  disable: { type: Boolean, required: false, default: false},
  sku: { type: String, required: false, default: false},
});

export const AddorderModel = mongoose.model("orderdetails", addorderSchema);
